/**
 * Autoload file generated by using command `najs-cli autoload`
 *
 * You can changed files list by editing `autoload.json` file and re-run the command
 */

// "bootstrap/**/*.ts"
import './bootstrap/ExpressApp'
import './bootstrap/Logger'

// "routes/**/*.ts"
import './routes/api'
import './routes/web'

// "app/**/*.ts"
import './app/Http/Controllers/TodoController'
import './app/Http/HttpKernel'