/**
 * Autoload file generated by using command `najs-cli autoload`
 *
 * You can changed files list by editing `autoload.json` file and re-run the command
 */

// "routes/**/*.ts"
import './routes/api'
import './routes/Facade'
import './routes/web'

// "app/**/*.ts"
import './app/Http/Controllers/TodoController'
import './app/Http/HttpKernel'
import './app/Providers/RouteServiceProvider'